/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management_system;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","1234");
        }
        catch(SQLException e) {
        }
    }
    
    public DashboardFrame(String id) {
        this.id = id;
        initComponents();
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","1234");
            String sql = "select ClubHead from Club where ClubHead=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1,id);
            rs = ps.executeQuery();
            if(rs.next())
                this.admin = true;
            else
                this.admin = false;
            
        }
        catch(SQLException e) {
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardLabel = new javax.swing.JLabel();
        viewEventsToJoinButton = new javax.swing.JButton();
        joinNewClubButton = new javax.swing.JButton();
        browseJoinedEventsButton = new javax.swing.JButton();
        viewAnnouncementsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboardLabel.setText("DASHBOARD");

        viewEventsToJoinButton.setText("View Events To Join");
        viewEventsToJoinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEventsToJoinButtonActionPerformed(evt);
            }
        });

        joinNewClubButton.setText("Join New Club");
        joinNewClubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinNewClubButtonActionPerformed(evt);
            }
        });

        browseJoinedEventsButton.setText("Browse Joined Events");
        browseJoinedEventsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseJoinedEventsButtonActionPerformed(evt);
            }
        });

        viewAnnouncementsButton.setText("View Announcements");
        viewAnnouncementsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAnnouncementsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(dashboardLabel)
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewAnnouncementsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(joinNewClubButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewEventsToJoinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(browseJoinedEventsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardLabel)
                .addGap(52, 52, 52)
                .addComponent(viewAnnouncementsButton)
                .addGap(18, 18, 18)
                .addComponent(viewEventsToJoinButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(joinNewClubButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browseJoinedEventsButton)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewEventsToJoinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEventsToJoinButtonActionPerformed
        // TODO add your handling code here:
        new ViewEventsToJoinFrame(id,admin,conn).setVisible(true);
    }//GEN-LAST:event_viewEventsToJoinButtonActionPerformed

    private void browseJoinedEventsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseJoinedEventsButtonActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select count(*) from Attendees where StudentID=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1,id);
            rs = ps.executeQuery();
            rs.next();
            if(rs.getInt(1)>0) {
                new BrowseJoinedEventsFrame(id).setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, "You have not joined any events!");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_browseJoinedEventsButtonActionPerformed

    private void joinNewClubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinNewClubButtonActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select count(*) as ct from ((select ClubID from Club) minus (select ClubID from Members where StudentID=?))";
            ps = conn.prepareStatement(sql);
            ps.setString(1, id);
            rs = ps.executeQuery();
            //rs.next();
            if(rs.next()) {
                if (rs.getInt(1) > 0) {
                    new JoinNewClubFrame(id).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No new clubs to join!");
                }
            }
            else
                System.out.println("Pls why");
            
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_joinNewClubButtonActionPerformed

    private void viewAnnouncementsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAnnouncementsButtonActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select count(*) as ct from Announcement a,Members m where a.ClubID=m.ClubID and m.StudentID=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, id);
            rs = ps.executeQuery();
            rs.next();
            if(admin || rs.getInt("ct")>0){
                new viewAnnouncementsFrame(id,admin,conn).setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, "No Announcements to View!");
            
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_viewAnnouncementsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }
    
    String id;
    Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    Boolean admin;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseJoinedEventsButton;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JButton joinNewClubButton;
    private javax.swing.JButton viewAnnouncementsButton;
    private javax.swing.JButton viewEventsToJoinButton;
    // End of variables declaration//GEN-END:variables
}
