/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management_system;

import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class InsertAnnouncementFrame extends javax.swing.JFrame {

    /**
     * Creates new form InsertAnnouncementFrame
     */
    public InsertAnnouncementFrame() {
        initComponents();
    }
    
    public InsertAnnouncementFrame(String id, Connection conn) {
        this.id = id;
        this.conn = conn;
        hmap = new HashMap();
        initComponents();
        clubIdComboBox.removeAllItems();
        try {
            String sql = "select ClubName,ClubID from Club where ClubID in (select i.ClubID from Club i where i.ClubHead=?)";
            ps = conn.prepareStatement(sql);
            ps.setString(1,id);
            rs = ps.executeQuery();
            while(rs.next()) {
                hmap.put(rs.getString(1),rs.getString(2));
                clubIdComboBox.addItem(rs.getString(1));
            }
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        announcementIdLabel = new javax.swing.JLabel();
        clubIdLabel = new javax.swing.JLabel();
        atitleLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        aidTextField = new javax.swing.JTextField();
        clubIdComboBox = new javax.swing.JComboBox<>();
        atitleTextField = new javax.swing.JTextField();
        descTextField = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setText("INSERT ANNOUNCEMENT");

        announcementIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        announcementIdLabel.setText("Announcement ID");

        clubIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clubIdLabel.setText("Club ID");

        atitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atitleLabel.setText("Title");

        descLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descLabel.setText("Description");

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(announcementIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clubIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aidTextField)
                            .addComponent(clubIdComboBox, 0, 346, Short.MAX_VALUE)
                            .addComponent(atitleTextField)
                            .addComponent(descTextField))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(insertButton)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(announcementIdLabel)
                    .addComponent(aidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clubIdLabel)
                    .addComponent(clubIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atitleLabel)
                    .addComponent(atitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(insertButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        
        try {
            String sql = "insert into Announcement values(?,?,?,?)";
            ps = conn.prepareStatement(sql);
            ps.setString(1, aidTextField.getText());
            ps.setString(2,hmap.get((String)clubIdComboBox.getSelectedItem()));
            ps.setString(3,atitleTextField.getText());
            ps.setString(4,descTextField.getText());
            
            ps.executeQuery();
            
            JOptionPane.showMessageDialog(this,"Inserted!");
            this.setVisible(false);
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertAnnouncementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertAnnouncementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertAnnouncementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertAnnouncementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertAnnouncementFrame().setVisible(true);
            }
        });
    }
    
    String id;
    Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    HashMap<String,String> hmap;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aidTextField;
    private javax.swing.JLabel announcementIdLabel;
    private javax.swing.JLabel atitleLabel;
    private javax.swing.JTextField atitleTextField;
    private javax.swing.JComboBox<String> clubIdComboBox;
    private javax.swing.JLabel clubIdLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField descTextField;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
